<?php

namespace Database\Seeders;

use App\Models\Icd10Diagnosis;
use Illuminate\Database\Seeder;

class Icd10Seeder extends Seeder
{
    public function run(): void
    {
        $diagnoses = [
            // Neoplasma (C00-D48) — tambahan
            ['C00', 'Neoplasma bibir', 'Neoplasma'],
            ['C01', 'Neoplasma pangkal lidah', 'Neoplasma'],
            ['C02', 'Neoplasma lidah bagian lain', 'Neoplasma'],
            ['C03', 'Neoplasma gusi', 'Neoplasma'],
            ['C04', 'Neoplasma dasar mulut', 'Neoplasma'],
            ['C05', 'Neoplasma langit-langit mulut', 'Neoplasma'],
            ['C06', 'Neoplasma mulut bagian lain', 'Neoplasma'],
            ['C07', 'Neoplasma kelenjar parotis', 'Neoplasma'],
            ['C08', 'Neoplasma kelenjar ludah lainnya', 'Neoplasma'],
            ['C09', 'Neoplasma tonsil', 'Neoplasma'],
            ['C10', 'Neoplasma orofaring', 'Neoplasma'],
            ['C11', 'Neoplasma nasofaring', 'Neoplasma'],
            ['C12', 'Neoplasma sinus piriformis', 'Neoplasma'],
            ['C13', 'Neoplasma hipofaring', 'Neoplasma'],
            ['C14', 'Neoplasma faring lainnya', 'Neoplasma'],
            ['C15', 'Neoplasma esofagus', 'Neoplasma'],
            ['C17', 'Neoplasma usus halus', 'Neoplasma'],
            ['C19', 'Neoplasma sigmoid', 'Neoplasma'],
            ['C21', 'Neoplasma anus dan kanal anal', 'Neoplasma'],
            ['C23', 'Neoplasma kandung empedu', 'Neoplasma'],
            ['C24', 'Neoplasma saluran empedu lainnya', 'Neoplasma'],
            ['C25', 'Neoplasma pankreas', 'Neoplasma'],
            ['C30', 'Neoplasma rongga hidung dan telinga tengah', 'Neoplasma'],
            ['C31', 'Neoplasma sinus aksesorius', 'Neoplasma'],
            ['C32', 'Neoplasma laring', 'Neoplasma'],
            ['C33', 'Neoplasma trakea', 'Neoplasma'],
            ['C43', 'Melanoma ganas pada kulit', 'Neoplasma'],
            ['C44', 'Neoplasma kulit lainnya', 'Neoplasma'],
            ['C45', 'Mesotelioma', 'Neoplasma'],
            ['C46', 'Sarkoma Kaposi', 'Neoplasma'],
            ['C47', 'Neoplasma saraf perifer', 'Neoplasma'],
            ['C48', 'Neoplasma retroperitoneal', 'Neoplasma'],
            ['C49', 'Neoplasma jaringan ikat dan lunak', 'Neoplasma'],
            ['C50', 'Neoplasma payudara', 'Neoplasma'],
            ['C51', 'Neoplasma vulva', 'Neoplasma'],
            ['C52', 'Neoplasma vagina', 'Neoplasma'],
            ['C53', 'Neoplasma serviks uteri', 'Neoplasma'],
            ['C54', 'Neoplasma korpus uteri', 'Neoplasma'],
            ['C55', 'Neoplasma uterus tidak spesifik', 'Neoplasma'],
            ['C56', 'Neoplasma ovarium', 'Neoplasma'],
            ['C60', 'Neoplasma penis', 'Neoplasma'],
            ['C61', 'Neoplasma prostat', 'Neoplasma'],
            ['C62', 'Neoplasma testis', 'Neoplasma'],
            ['C63', 'Neoplasma alat kelamin pria lainnya', 'Neoplasma'],
            ['C64', 'Neoplasma ginjal', 'Neoplasma'],
            ['C65', 'Neoplasma pelvis renalis', 'Neoplasma'],
            ['C66', 'Neoplasma ureter', 'Neoplasma'],
            ['C67', 'Neoplasma kandung kemih', 'Neoplasma'],
            ['C68', 'Neoplasma saluran kemih lainnya', 'Neoplasma'],
            ['C69', 'Neoplasma mata dan adneksa', 'Neoplasma'],
            ['C70', 'Neoplasma meninges', 'Neoplasma'],
            ['C71', 'Neoplasma otak', 'Neoplasma'],
            ['C72', 'Neoplasma medula spinalis', 'Neoplasma'],
            ['C73', 'Neoplasma tiroid', 'Neoplasma'],
            ['C74', 'Neoplasma kelenjar adrenal', 'Neoplasma'],
            ['C75', 'Neoplasma kelenjar endokrin lainnya', 'Neoplasma'],
            ['C76', 'Neoplasma lokasi tidak spesifik', 'Neoplasma'],
            ['C77', 'Neoplasma kelenjar getah bening sekunder', 'Neoplasma'],
            ['C78', 'Neoplasma sekunder sistem pernapasan', 'Neoplasma'],
            ['C79', 'Neoplasma sekunder lokasi lainnya', 'Neoplasma'],
            ['C81', 'Penyakit Hodgkin', 'Neoplasma'],
            ['C82', 'Limfoma non-Hodgkin folikuler', 'Neoplasma'],
            ['C83', 'Limfoma non-Hodgkin difus', 'Neoplasma'],
            ['C85', 'Limfoma non-Hodgkin lainnya', 'Neoplasma'],
            ['C88', 'Penyakit imunoproliferatif ganas', 'Neoplasma'],
            ['C90', 'Mieloma multipel', 'Neoplasma'],
            ['C91', 'Leukemia limfoid', 'Neoplasma'],
            ['C92', 'Leukemia mieloid', 'Neoplasma'],
            ['C93', 'Leukemia monositik', 'Neoplasma'],
            ['C94', 'Leukemia lainnya', 'Neoplasma'],
            ['C95', 'Leukemia tidak spesifik', 'Neoplasma'],
            ['D00', 'Karsinoma in situ rongga mulut', 'Neoplasma'],
            ['D01', 'Karsinoma in situ saluran cerna', 'Neoplasma'],
            ['D02', 'Karsinoma in situ pernapasan', 'Neoplasma'],
            ['D05', 'Karsinoma in situ payudara', 'Neoplasma'],
            ['D06', 'Karsinoma in situ serviks', 'Neoplasma'],
            ['D07', 'Karsinoma in situ genital lainnya', 'Neoplasma'],
            ['D09', 'Karsinoma in situ lainnya', 'Neoplasma'],
            ['D10', 'Neoplasma jinak mulut dan faring', 'Neoplasma'],
            ['D11', 'Neoplasma jinak kelenjar ludah', 'Neoplasma'],
            ['D12', 'Neoplasma jinak kolon', 'Neoplasma'],
            ['D13', 'Neoplasma jinak saluran cerna lainnya', 'Neoplasma'],
            ['D14', 'Neoplasma jinak pernapasan', 'Neoplasma'],
            ['D15', 'Neoplasma jinak intratoraks', 'Neoplasma'],
            ['D16', 'Neoplasma jinak tulang', 'Neoplasma'],
            ['D17', 'Tumor jinak jaringan lemak', 'Neoplasma'],
            ['D18', 'Hemangioma', 'Neoplasma'],
            ['D19', 'Tumor jinak mesotelial', 'Neoplasma'],
            ['D20', 'Tumor jinak retroperitoneal', 'Neoplasma'],
            ['D21', 'Tumor jinak jaringan lunak', 'Neoplasma'],
            ['D22', 'Nevus melanositik', 'Neoplasma'],
            ['D23', 'Tumor jinak kulit', 'Neoplasma'],
            ['D24', 'Tumor jinak payudara', 'Neoplasma'],
            ['D25', 'Leiomioma uteri', 'Neoplasma'],
            ['D26', 'Tumor jinak uterus lainnya', 'Neoplasma'],
            ['D27', 'Tumor jinak ovarium', 'Neoplasma'],
            ['D28', 'Tumor jinak genital wanita lainnya', 'Neoplasma'],
            ['D29', 'Tumor jinak genital pria', 'Neoplasma'],
            ['D30', 'Tumor jinak saluran kemih', 'Neoplasma'],
            ['D31', 'Tumor jinak mata', 'Neoplasma'],
            ['D32', 'Tumor jinak meninges', 'Neoplasma'],
            ['D33', 'Tumor jinak otak dan SSP', 'Neoplasma'],
            ['D34', 'Tumor jinak tiroid', 'Neoplasma'],
            ['D35', 'Tumor jinak kelenjar endokrin', 'Neoplasma'],
            ['D36', 'Tumor jinak lainnya', 'Neoplasma'],
            ['D37', 'Tumor dengan perilaku tidak pasti rongga mulut', 'Neoplasma'],
            ['D38', 'Tumor tidak pasti pernapasan', 'Neoplasma'],
            ['D39', 'Tumor tidak pasti genital wanita', 'Neoplasma'],
            ['D40', 'Tumor tidak pasti genital pria', 'Neoplasma'],
            ['D41', 'Tumor tidak pasti saluran kemih', 'Neoplasma'],
            ['D42', 'Tumor tidak pasti meninges', 'Neoplasma'],
            ['D43', 'Tumor tidak pasti otak dan SSP', 'Neoplasma'],
            ['D44', 'Tumor tidak pasti kelenjar endokrin', 'Neoplasma'],
            ['D45', 'Polisitemia vera', 'Neoplasma'],
            ['D46', 'Sindrom mielodisplastik', 'Neoplasma'],
            ['D47', 'Tumor tidak pasti jaringan limfoid', 'Neoplasma'],
            ['D48', 'Tumor tidak pasti lokasi lainnya', 'Neoplasma'],

            // Penyakit Darah (D50-D89)
            ['D50', 'Anemia defisiensi besi', 'Penyakit Darah'],
            ['D51', 'Anemia defisiensi vitamin B12', 'Penyakit Darah'],
            ['D52', 'Anemia defisiensi folat', 'Penyakit Darah'],
            ['D53', 'Anemia nutrisi lainnya', 'Penyakit Darah'],
            ['D55', 'Anemia akibat enzimopati', 'Penyakit Darah'],
            ['D56', 'Talassemia', 'Penyakit Darah'],
            ['D57', 'Penyakit sel sabit', 'Penyakit Darah'],
            ['D58', 'Anemia hemolitik herediter lainnya', 'Penyakit Darah'],
            ['D59', 'Anemia hemolitik didapat', 'Penyakit Darah'],
            ['D60', 'Aplasia sel darah merah didapat', 'Penyakit Darah'],
            ['D61', 'Anemia aplastik', 'Penyakit Darah'],
            ['D62', 'Anemia pasca perdarahan akut', 'Penyakit Darah'],
            ['D63', 'Anemia pada penyakit kronis', 'Penyakit Darah'],
            ['D64', 'Anemia lainnya', 'Penyakit Darah'],
            ['D65', 'Koagulasi intravaskular diseminata', 'Penyakit Darah'],
            ['D66', 'Defisiensi faktor VIII', 'Penyakit Darah'],
            ['D67', 'Defisiensi faktor IX', 'Penyakit Darah'],
            ['D68', 'Defek koagulasi lainnya', 'Penyakit Darah'],
            ['D69', 'Purpura dan kondisi hemoragik', 'Penyakit Darah'],
            ['D70', 'Agranulositosis', 'Penyakit Darah'],
            ['D71', 'Gangguan fungsi neutrofil', 'Penyakit Darah'],
            ['D72', 'Leukositosis', 'Penyakit Darah'],
            ['D73', 'Penyakit limpa', 'Penyakit Darah'],
            ['D74', 'Methemoglobinemia', 'Penyakit Darah'],
            ['D75', 'Penyakit darah lainnya', 'Penyakit Darah'],
            ['D76', 'Limfohistiositosis hemofagositik', 'Penyakit Darah'],
            ['D80', 'Defisiensi imun humoral', 'Penyakit Darah'],
            ['D81', 'Defisiensi imun kombinasi', 'Penyakit Darah'],
            ['D82', 'Defisiensi imun terkait defek lainnya', 'Penyakit Darah'],
            ['D83', 'Defisiensi imun variabel umum', 'Penyakit Darah'],
            ['D84', 'Defisiensi imun lainnya', 'Penyakit Darah'],
            ['D86', 'Sarkoidosis', 'Penyakit Darah'],
            ['D89', 'Gangguan sistem imun lainnya', 'Penyakit Darah'],

            // Penyakit Endokrin & Metabolik (E00-E90)
            ['E00', 'Sindrom defisiensi yodium kongenital', 'Endokrin & Metabolik'],
            ['E01', 'Gangguan tiroid terkait yodium', 'Endokrin & Metabolik'],
            ['E02', 'Defisiensi yodium subklinis', 'Endokrin & Metabolik'],
            ['E03', 'Hipotiroidisme', 'Endokrin & Metabolik'],
            ['E04', 'Gondok non-toksik', 'Endokrin & Metabolik'],
            ['E05', 'Hipertiroidisme', 'Endokrin & Metabolik'],
            ['E06', 'Tiroiditis', 'Endokrin & Metabolik'],
            ['E07', 'Gangguan tiroid lainnya', 'Endokrin & Metabolik'],
            ['E10', 'Diabetes melitus tipe 1', 'Endokrin & Metabolik'],
            ['E11', 'Diabetes melitus tipe 2', 'Endokrin & Metabolik'],
            ['E12', 'Diabetes melitus terkait malnutrisi', 'Endokrin & Metabolik'],
            ['E13', 'Diabetes melitus tipe spesifik lainnya', 'Endokrin & Metabolik'],
            ['E14', 'Diabetes melitus tidak spesifik', 'Endokrin & Metabolik'],
            ['E15', 'Koma hipoglikemik', 'Endokrin & Metabolik'],
            ['E16', 'Gangguan sekresi insulin lainnya', 'Endokrin & Metabolik'],
            ['E20', 'Hipoparatiroidisme', 'Endokrin & Metabolik'],
            ['E21', 'Hiperparatiroidisme', 'Endokrin & Metabolik'],
            ['E22', 'Hiperfungsi kelenjar pituitari', 'Endokrin & Metabolik'],
            ['E23', 'Hipofungsi kelenjar pituitari', 'Endokrin & Metabolik'],
            ['E24', 'Sindrom Cushing', 'Endokrin & Metabolik'],
            ['E25', 'Gangguan adrenal genital', 'Endokrin & Metabolik'],
            ['E26', 'Hiperaldosteronisme', 'Endokrin & Metabolik'],
            ['E27', 'Gangguan kelenjar adrenal lainnya', 'Endokrin & Metabolik'],
            ['E28', 'Disfungsi ovarium', 'Endokrin & Metabolik'],
            ['E29', 'Disfungsi testis', 'Endokrin & Metabolik'],
            ['E30', 'Gangguan pubertas', 'Endokrin & Metabolik'],
            ['E31', 'Disfungsi poliglandular', 'Endokrin & Metabolik'],
            ['E32', 'Penyakit timus', 'Endokrin & Metabolik'],
            ['E34', 'Gangguan endokrin lainnya', 'Endokrin & Metabolik'],
            ['E40', 'Kwashiorkor', 'Endokrin & Metabolik'],
            ['E41', 'Marasmus', 'Endokrin & Metabolik'],
            ['E42', 'Marasmik kwashiorkor', 'Endokrin & Metabolik'],
            ['E43', 'Malnutrisi berat', 'Endokrin & Metabolik'],
            ['E44', 'Malnutrisi sedang dan ringan', 'Endokrin & Metabolik'],
            ['E45', 'Retardasi pertumbuhan malnutrisi', 'Endokrin & Metabolik'],
            ['E46', 'Malnutrisi tidak spesifik', 'Endokrin & Metabolik'],
            ['E50', 'Defisiensi vitamin A', 'Endokrin & Metabolik'],
            ['E51', 'Defisiensi vitamin B1', 'Endokrin & Metabolik'],
            ['E52', 'Defisiensi vitamin B3', 'Endokrin & Metabolik'],
            ['E53', 'Defisiensi vitamin B lainnya', 'Endokrin & Metabolik'],
            ['E54', 'Defisiensi vitamin C', 'Endokrin & Metabolik'],
            ['E55', 'Defisiensi vitamin D', 'Endokrin & Metabolik'],
            ['E56', 'Defisiensi vitamin lainnya', 'Endokrin & Metabolik'],
            ['E58', 'Defisiensi kalsium', 'Endokrin & Metabolik'],
            ['E59', 'Defisiensi selenium', 'Endokrin & Metabolik'],
            ['E60', 'Defisiensi seng', 'Endokrin & Metabolik'],
            ['E61', 'Defisiensi mineral lainnya', 'Endokrin & Metabolik'],
            ['E63', 'Defisiensi nutrisi lainnya', 'Endokrin & Metabolik'],
            ['E64', 'Sekuele malnutrisi', 'Endokrin & Metabolik'],
            ['E65', 'Obesitas lokal', 'Endokrin & Metabolik'],
            ['E66', 'Obesitas', 'Endokrin & Metabolik'],
            ['E67', 'Kelebihan nutrisi lainnya', 'Endokrin & Metabolik'],
            ['E68', 'Sekuele kelebihan nutrisi', 'Endokrin & Metabolik'],
            ['E70', 'Gangguan metabolisme fenilalanin', 'Endokrin & Metabolik'],
            ['E71', 'Gangguan metabolisme asam amino rantai', 'Endokrin & Metabolik'],
            ['E72', 'Gangguan metabolisme asam amino lainnya', 'Endokrin & Metabolik'],
            ['E73', 'Defisiensi laktase', 'Endokrin & Metabolik'],
            ['E74', 'Gangguan metabolisme karbohidrat', 'Endokrin & Metabolik'],
            ['E75', 'Gangguan metabolisme sfingolipid', 'Endokrin & Metabolik'],
            ['E76', 'Gangguan metabolisme glikosaminoglikan', 'Endokrin & Metabolik'],
            ['E77', 'Gangguan metabolisme glikoprotein', 'Endokrin & Metabolik'],
            ['E78', 'Gangguan metabolisme lipoprotein', 'Endokrin & Metabolik'],
            ['E79', 'Gangguan metabolisme purin dan pirimidin', 'Endokrin & Metabolik'],
            ['E80', 'Gangguan metabolisme porfirin dan bilirubin', 'Endokrin & Metabolik'],
            ['E83', 'Gangguan metabolisme mineral', 'Endokrin & Metabolik'],
            ['E84', 'Fibrosis kistik', 'Endokrin & Metabolik'],
            ['E85', 'Amiloidosis', 'Endokrin & Metabolik'],
            ['E86', 'Deplesi volume cairan', 'Endokrin & Metabolik'],
            ['E87', 'Gangguan keseimbangan cairan dan elektrolit', 'Endokrin & Metabolik'],
            ['E88', 'Gangguan metabolik lainnya', 'Endokrin & Metabolik'],
            ['E89', 'Gangguan endokrin pasca-prosedur', 'Endokrin & Metabolik'],

            // Gangguan Mental (F00-F99)
            ['F00', 'Demensia Alzheimer', 'Gangguan Mental'],
            ['F01', 'Demensia vaskular', 'Gangguan Mental'],
            ['F02', 'Demensia penyakit lain', 'Gangguan Mental'],
            ['F03', 'Demensia tidak spesifik', 'Gangguan Mental'],
            ['F04', 'Sindrom amnestik organik', 'Gangguan Mental'],
            ['F05', 'Delirium', 'Gangguan Mental'],
            ['F06', 'Gangguan mental organik lainnya', 'Gangguan Mental'],
            ['F07', 'Gangguan kepribadian organik', 'Gangguan Mental'],
            ['F09', 'Gangguan mental organik tidak spesifik', 'Gangguan Mental'],
            ['F10', 'Gangguan mental akibat alkohol', 'Gangguan Mental'],
            ['F11', 'Gangguan mental akibat opioid', 'Gangguan Mental'],
            ['F12', 'Gangguan mental akibat kanabis', 'Gangguan Mental'],
            ['F13', 'Gangguan mental akibat sedatif', 'Gangguan Mental'],
            ['F14', 'Gangguan mental akibat kokain', 'Gangguan Mental'],
            ['F15', 'Gangguan mental akibat stimulan', 'Gangguan Mental'],
            ['F16', 'Gangguan mental akibat halusinogen', 'Gangguan Mental'],
            ['F17', 'Gangguan mental akibat tembakau', 'Gangguan Mental'],
            ['F18', 'Gangguan mental akibat pelarut', 'Gangguan Mental'],
            ['F19', 'Gangguan mental akibat zat multipel', 'Gangguan Mental'],
            ['F20', 'Skizofrenia', 'Gangguan Mental'],
            ['F21', 'Gangguan skizotipal', 'Gangguan Mental'],
            ['F22', 'Gangguan waham menetap', 'Gangguan Mental'],
            ['F23', 'Gangguan psikotik akut', 'Gangguan Mental'],
            ['F24', 'Gangguan waham terinduksi', 'Gangguan Mental'],
            ['F25', 'Gangguan skizoafektif', 'Gangguan Mental'],
            ['F28', 'Gangguan psikotik non-organik lainnya', 'Gangguan Mental'],
            ['F29', 'Psikosis non-organik tidak spesifik', 'Gangguan Mental'],
            ['F30', 'Episode manik', 'Gangguan Mental'],
            ['F31', 'Gangguan bipolar', 'Gangguan Mental'],
            ['F32', 'Episode depresif', 'Gangguan Mental'],
            ['F33', 'Gangguan depresif berulang', 'Gangguan Mental'],
            ['F34', 'Gangguan mood menetap', 'Gangguan Mental'],
            ['F38', 'Gangguan mood lainnya', 'Gangguan Mental'],
            ['F39', 'Gangguan mood tidak spesifik', 'Gangguan Mental'],
            ['F40', 'Gangguan fobia', 'Gangguan Mental'],
            ['F41', 'Gangguan kecemasan', 'Gangguan Mental'],
            ['F42', 'Gangguan obsesif-kompulsif', 'Gangguan Mental'],
            ['F43', 'Reaksi stres berat', 'Gangguan Mental'],
            ['F44', 'Gangguan disosiatif', 'Gangguan Mental'],
            ['F45', 'Gangguan somatoform', 'Gangguan Mental'],
            ['F48', 'Gangguan neurotik lainnya', 'Gangguan Mental'],
            ['F50', 'Gangguan makan', 'Gangguan Mental'],
            ['F51', 'Gangguan tidur non-organik', 'Gangguan Mental'],
            ['F52', 'Disfungsi seksual non-organik', 'Gangguan Mental'],
            ['F53', 'Gangguan mental terkait nifas', 'Gangguan Mental'],
            ['F54', 'Faktor psikologis pada penyakit fisik', 'Gangguan Mental'],
            ['F55', 'Penyalahgunaan zat non-adiktif', 'Gangguan Mental'],
            ['F59', 'Sindrom perilaku lainnya', 'Gangguan Mental'],
            ['F60', 'Gangguan kepribadian spesifik', 'Gangguan Mental'],
            ['F61', 'Gangguan kepribadian campuran', 'Gangguan Mental'],
            ['F62', 'Perubahan kepribadian menetap', 'Gangguan Mental'],
            ['F63', 'Gangguan impuls', 'Gangguan Mental'],
            ['F64', 'Gangguan identitas gender', 'Gangguan Mental'],
            ['F65', 'Gangguan preferensi seksual', 'Gangguan Mental'],
            ['F66', 'Gangguan perkembangan seksual', 'Gangguan Mental'],
            ['F68', 'Gangguan kepribadian lainnya', 'Gangguan Mental'],
            ['F69', 'Gangguan kepribadian tidak spesifik', 'Gangguan Mental'],
            ['F70', 'Retardasi mental ringan', 'Gangguan Mental'],
            ['F71', 'Retardasi mental sedang', 'Gangguan Mental'],
            ['F72', 'Retardasi mental berat', 'Gangguan Mental'],
            ['F73', 'Retardasi mental sangat berat', 'Gangguan Mental'],
            ['F78', 'Retardasi mental lainnya', 'Gangguan Mental'],
            ['F79', 'Retardasi mental tidak spesifik', 'Gangguan Mental'],
            ['F80', 'Gangguan bicara dan bahasa', 'Gangguan Mental'],
            ['F81', 'Gangguan belajar', 'Gangguan Mental'],
            ['F82', 'Gangguan motorik', 'Gangguan Mental'],
            ['F83', 'Gangguan perkembangan campuran', 'Gangguan Mental'],
            ['F84', 'Gangguan spektrum autisme', 'Gangguan Mental'],
            ['F88', 'Gangguan perkembangan lainnya', 'Gangguan Mental'],
            ['F89', 'Gangguan perkembangan tidak spesifik', 'Gangguan Mental'],
            ['F90', 'Gangguan hiperkinetik (ADHD)', 'Gangguan Mental'],
            ['F91', 'Gangguan perilaku', 'Gangguan Mental'],
            ['F92', 'Gangguan perilaku dan emosi campuran', 'Gangguan Mental'],
            ['F93', 'Gangguan emosi anak', 'Gangguan Mental'],
            ['F94', 'Gangguan fungsi sosial anak', 'Gangguan Mental'],
            ['F95', 'Gangguan tik', 'Gangguan Mental'],
            ['F98', 'Gangguan perilaku anak lainnya', 'Gangguan Mental'],
            ['F99', 'Gangguan mental tidak spesifik', 'Gangguan Mental'],

            // Penyakit Sistem Saraf (G00-G99)
            ['G00', 'Meningitis bakterial', 'Sistem Saraf'],
            ['G01', 'Meningitis pada penyakit lain', 'Sistem Saraf'],
            ['G02', 'Meningitis pada infeksi lain', 'Sistem Saraf'],
            ['G03', 'Meningitis penyebab lain', 'Sistem Saraf'],
            ['G04', 'Ensefalitis dan mielitis', 'Sistem Saraf'],
            ['G05', 'Ensefalitis pada penyakit lain', 'Sistem Saraf'],
            ['G06', 'Abses intrakranial dan intraspinal', 'Sistem Saraf'],
            ['G07', 'Abses SSP pada penyakit lain', 'Sistem Saraf'],
            ['G08', 'Flebitis intrakranial', 'Sistem Saraf'],
            ['G09', 'Sekuele penyakit SSP', 'Sistem Saraf'],
            ['G10', 'Penyakit Huntington', 'Sistem Saraf'],
            ['G11', 'Ataksia herediter', 'Sistem Saraf'],
            ['G12', 'Penyakit motor neuron', 'Sistem Saraf'],
            ['G13', 'Atrofi sistemik', 'Sistem Saraf'],
            ['G20', 'Penyakit Parkinson', 'Sistem Saraf'],
            ['G21', 'Parkinsonisme sekunder', 'Sistem Saraf'],
            ['G22', 'Parkinsonisme pada penyakit lain', 'Sistem Saraf'],
            ['G23', 'Penyakit ganglion basal lainnya', 'Sistem Saraf'],
            ['G24', 'Distonia', 'Sistem Saraf'],
            ['G25', 'Gangguan ekstrapiramidal lainnya', 'Sistem Saraf'],
            ['G30', 'Penyakit Alzheimer', 'Sistem Saraf'],
            ['G31', 'Penyakit degeneratif SSP lainnya', 'Sistem Saraf'],
            ['G32', 'Degenerasi SSP pada penyakit lain', 'Sistem Saraf'],
            ['G35', 'Sklerosis multipel', 'Sistem Saraf'],
            ['G36', 'Mielitis transversa akut', 'Sistem Saraf'],
            ['G37', 'Penyakit demielinasi SSP lainnya', 'Sistem Saraf'],
            ['G40', 'Epilepsi', 'Sistem Saraf'],
            ['G41', 'Status epileptikus', 'Sistem Saraf'],
            ['G43', 'Migren', 'Sistem Saraf'],
            ['G44', 'Sakit kepala lainnya', 'Sistem Saraf'],
            ['G45', 'Serangan iskemik serebral transien', 'Sistem Saraf'],
            ['G46', 'Sindrom vaskular serebral', 'Sistem Saraf'],
            ['G47', 'Gangguan tidur', 'Sistem Saraf'],
            ['G50', 'Gangguan saraf trigeminal', 'Sistem Saraf'],
            ['G51', 'Gangguan saraf fasial', 'Sistem Saraf'],
            ['G52', 'Gangguan saraf kranial lainnya', 'Sistem Saraf'],
            ['G53', 'Gangguan saraf kranial pada penyakit lain', 'Sistem Saraf'],
            ['G54', 'Gangguan pleksus saraf', 'Sistem Saraf'],
            ['G55', 'Kompresi saraf pada penyakit lain', 'Sistem Saraf'],
            ['G56', 'Sindrom terowongan karpal', 'Sistem Saraf'],
            ['G57', 'Gangguan saraf perifer tungkai', 'Sistem Saraf'],
            ['G58', 'Neuropati mononeural lainnya', 'Sistem Saraf'],
            ['G59', 'Neuropati mononeural pada penyakit lain', 'Sistem Saraf'],
            ['G60', 'Neuropati herediter', 'Sistem Saraf'],
            ['G61', 'Poliradikulopati inflamasi', 'Sistem Saraf'],
            ['G62', 'Polineuropati lainnya', 'Sistem Saraf'],
            ['G63', 'Polineuropati pada penyakit lain', 'Sistem Saraf'],
            ['G64', 'Gangguan saraf perifer lainnya', 'Sistem Saraf'],
            ['G70', 'Miestenia gravis', 'Sistem Saraf'],
            ['G71', 'Gangguan otot primer', 'Sistem Saraf'],
            ['G72', 'Miopati lainnya', 'Sistem Saraf'],
            ['G73', 'Miopati pada penyakit lain', 'Sistem Saraf'],
            ['G80', 'Serebral palsi', 'Sistem Saraf'],
            ['G81', 'Hemiplegia', 'Sistem Saraf'],
            ['G82', 'Paraplegia dan tetraplegia', 'Sistem Saraf'],
            ['G83', 'Sindrom paralitik lainnya', 'Sistem Saraf'],
            ['G90', 'Gangguan sistem saraf otonom', 'Sistem Saraf'],
            ['G91', 'Hidrosefalus', 'Sistem Saraf'],
            ['G92', 'Ensefalopati toksik', 'Sistem Saraf'],
            ['G93', 'Gangguan otak lainnya', 'Sistem Saraf'],
            ['G94', 'Gangguan otak pada penyakit lain', 'Sistem Saraf'],
            ['G95', 'Penyakit medula spinalis', 'Sistem Saraf'],
            ['G96', 'Gangguan SSP lainnya', 'Sistem Saraf'],
            ['G97', 'Gangguan SSP pasca-prosedur', 'Sistem Saraf'],
            ['G98', 'Gangguan sistem saraf lainnya', 'Sistem Saraf'],
        ];

        $count = 0;
        foreach ($diagnoses as [$code, $name, $category]) {
            Icd10Diagnosis::firstOrCreate(
                ['code' => $code],
                ['name' => $name, 'category' => $category, 'is_active' => true]
            );
            $count++;
        }

        $this->command->info("ICD-10 codes added: {$count} codes");
    }
}
