<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $procedures = [
            ['code' => '01.11', 'name' => 'Biopsi otak', 'category' => 'Sistem Saraf'],
            ['code' => '01.31', 'name' => 'Biopsi incisional serebrum', 'category' => 'Sistem Saraf'],
            ['code' => '01.59', 'name' => 'Eksisi otak lainnya', 'category' => 'Sistem Saraf'],
            ['code' => '03.31', 'name' => 'Pungsi lumbal (spinal tap)', 'category' => 'Sistem Saraf'],
            ['code' => '04.04', 'name' => 'Insisi saraf kranial dan perifer', 'category' => 'Sistem Saraf'],
            ['code' => '06.13', 'name' => 'Biopsi kelenjar tiroid', 'category' => 'Endokrin'],
            ['code' => '06.31', 'name' => 'Tiroidectomy total', 'category' => 'Endokrin'],
            ['code' => '07.21', 'name' => 'Biopsi adrenal', 'category' => 'Endokrin'],
            ['code' => '08.11', 'name' => 'Biopsi kelopak mata', 'category' => 'Mata'],
            ['code' => '08.51', 'name' => 'Kantotomi', 'category' => 'Mata'],
            ['code' => '09.11', 'name' => 'Biopsi kelenjar lakrimal', 'category' => 'Mata'],
            ['code' => '10.31', 'name' => 'Biopsi konjungtiva', 'category' => 'Mata'],
            ['code' => '12.11', 'name' => 'Iridotomi', 'category' => 'Mata'],
            ['code' => '13.11', 'name' => 'Ekstraksi katarak intrakapsular', 'category' => 'Mata'],
            ['code' => '13.19', 'name' => 'Ekstraksi katarak ekstrakapsular', 'category' => 'Mata'],
            ['code' => '13.41', 'name' => 'Fakoemulsifikasi katarak', 'category' => 'Mata'],
            ['code' => '16.01', 'name' => 'Orbitotomi', 'category' => 'Mata'],
            ['code' => '18.11', 'name' => 'Otoskopi', 'category' => 'Telinga'],
            ['code' => '19.11', 'name' => 'Stapedektomi', 'category' => 'Telinga'],
            ['code' => '20.01', 'name' => 'Miringotomi (pasang pipa ventilasi)', 'category' => 'Telinga'],
            ['code' => '20.21', 'name' => 'Mastoidektomi', 'category' => 'Telinga'],
            ['code' => '21.01', 'name' => 'Kontrol epistaksis', 'category' => 'Hidung'],
            ['code' => '21.31', 'name' => 'Polipektomi hidung', 'category' => 'Hidung'],
            ['code' => '21.51', 'name' => 'Rinoplasti', 'category' => 'Hidung'],
            ['code' => '22.11', 'name' => 'Biopsi sinus nasal', 'category' => 'Sinus'],
            ['code' => '23.01', 'name' => 'Ekstraksi gigi', 'category' => 'Gigi'],
            ['code' => '24.31', 'name' => 'Eksisi lesi gusi', 'category' => 'Gigi'],
            ['code' => '25.11', 'name' => 'Biopsi lidah', 'category' => 'Mulut'],
            ['code' => '26.11', 'name' => 'Biopsi kelenjar liur', 'category' => 'Mulut'],
            ['code' => '27.21', 'name' => 'Biopsi uvula', 'category' => 'Mulut'],
            ['code' => '28.11', 'name' => 'Tonsilektomi', 'category' => 'Tonsil'],
            ['code' => '28.31', 'name' => 'Adenoidektomi', 'category' => 'Tonsil'],
            ['code' => '29.11', 'name' => 'Faringoskopi', 'category' => 'Faring'],
            ['code' => '30.21', 'name' => 'Epiglotidektomi', 'category' => 'Laring'],
            ['code' => '31.41', 'name' => 'Trakeoskopi', 'category' => 'Trakea'],
            ['code' => '31.42', 'name' => 'Trakeostomi', 'category' => 'Trakea'],
            ['code' => '32.01', 'name' => 'Bronkoskopi', 'category' => 'Paru'],
            ['code' => '32.21', 'name' => 'Biopsi paru', 'category' => 'Paru'],
            ['code' => '32.41', 'name' => 'Lobektomi paru', 'category' => 'Paru'],
            ['code' => '33.22', 'name' => 'Torakoskopi', 'category' => 'Pleura'],
            ['code' => '34.01', 'name' => 'Torakosentesis', 'category' => 'Dada'],
            ['code' => '34.21', 'name' => 'Mediastinoskopi', 'category' => 'Mediastinum'],
            ['code' => '35.01', 'name' => 'Valvotomi jantung tertutup', 'category' => 'Jantung'],
            ['code' => '35.21', 'name' => 'Penggantian katup aorta', 'category' => 'Jantung'],
            ['code' => '35.22', 'name' => 'Penggantian katup mitral', 'category' => 'Jantung'],
            ['code' => '35.33', 'name' => 'Annuloplasti trikuspid', 'category' => 'Jantung'],
            ['code' => '36.01', 'name' => 'PTCA (balon angioplasti)', 'category' => 'Jantung'],
            ['code' => '36.03', 'name' => 'Angioplasti koroner terbuka', 'category' => 'Jantung'],
            ['code' => '36.11', 'name' => 'CABG (bypass jantung)', 'category' => 'Jantung'],
            ['code' => '37.11', 'name' => 'Kateterisasi jantung', 'category' => 'Jantung'],
            ['code' => '37.21', 'name' => 'Pemasangan pacemaker', 'category' => 'Jantung'],
            ['code' => '37.31', 'name' => 'Perikardiosentesis', 'category' => 'Jantung'],
            ['code' => '38.01', 'name' => 'Endarterektomi karotis', 'category' => 'Pembuluh Darah'],
            ['code' => '38.21', 'name' => 'Repair aneurisma aorta', 'category' => 'Pembuluh Darah'],
            ['code' => '38.31', 'name' => 'Stripping varises', 'category' => 'Pembuluh Darah'],
            ['code' => '38.41', 'name' => 'Shunt arteriovenosa', 'category' => 'Pembuluh Darah'],
            ['code' => '39.21', 'name' => 'AV fistula untuk dialisis', 'category' => 'Pembuluh Darah'],
            ['code' => '39.31', 'name' => 'Jahitan arteri', 'category' => 'Pembuluh Darah'],
            ['code' => '39.41', 'name' => 'Filter IVC', 'category' => 'Pembuluh Darah'],
            ['code' => '39.51', 'name' => 'Angioplasti non-koroner', 'category' => 'Pembuluh Darah'],
            ['code' => '40.11', 'name' => 'Biopsi kelenjar getah bening', 'category' => 'Limfatik'],
            ['code' => '40.31', 'name' => 'Diseksi kelenjar getah bening', 'category' => 'Limfatik'],
            ['code' => '41.01', 'name' => 'Biopsi sumsum tulang', 'category' => 'Hematologi'],
            ['code' => '41.31', 'name' => 'Splenektomi', 'category' => 'Hematologi'],
            ['code' => '42.11', 'name' => 'Esofagoskopi', 'category' => 'Saluran Cerna'],
            ['code' => '42.31', 'name' => 'Esofagektomi', 'category' => 'Saluran Cerna'],
            ['code' => '42.41', 'name' => 'Dilatasi esofagus', 'category' => 'Saluran Cerna'],
            ['code' => '43.11', 'name' => 'Gastroskopi', 'category' => 'Saluran Cerna'],
            ['code' => '43.31', 'name' => 'Gastrektomi', 'category' => 'Saluran Cerna'],
            ['code' => '43.41', 'name' => 'Piloroplasti', 'category' => 'Saluran Cerna'],
            ['code' => '44.01', 'name' => 'Vagotomi', 'category' => 'Saluran Cerna'],
            ['code' => '44.21', 'name' => 'Gastric bypass', 'category' => 'Saluran Cerna'],
            ['code' => '44.31', 'name' => 'Gastroenterostomi', 'category' => 'Saluran Cerna'],
            ['code' => '45.11', 'name' => 'Kolonoskopi', 'category' => 'Saluran Cerna'],
            ['code' => '45.21', 'name' => 'Apendiktomi', 'category' => 'Saluran Cerna'],
            ['code' => '45.31', 'name' => 'Kolektomi', 'category' => 'Saluran Cerna'],
            ['code' => '45.41', 'name' => 'Sigmoidoskopi', 'category' => 'Saluran Cerna'],
            ['code' => '46.01', 'name' => 'Kolostomi', 'category' => 'Saluran Cerna'],
            ['code' => '46.11', 'name' => 'Ileostomi', 'category' => 'Saluran Cerna'],
            ['code' => '47.01', 'name' => 'Kolesistektomi laparoskopi', 'category' => 'Saluran Cerna'],
            ['code' => '47.11', 'name' => 'Kolesistektomi terbuka', 'category' => 'Saluran Cerna'],
            ['code' => '48.21', 'name' => 'Proktosigmoidoskopi', 'category' => 'Saluran Cerna'],
            ['code' => '48.31', 'name' => 'Biopsi rektum', 'category' => 'Saluran Cerna'],
            ['code' => '49.01', 'name' => 'Hemoroidektomi', 'category' => 'Anus'],
            ['code' => '49.11', 'name' => 'Fissurektomi anal', 'category' => 'Anus'],
            ['code' => '50.01', 'name' => 'Biopsi hati', 'category' => 'Hepatobilier'],
            ['code' => '50.21', 'name' => 'Hepatektomi', 'category' => 'Hepatobilier'],
            ['code' => '51.01', 'name' => 'ERCP', 'category' => 'Hepatobilier'],
            ['code' => '51.21', 'name' => 'Kolesistektomi', 'category' => 'Hepatobilier'],
            ['code' => '52.01', 'name' => 'Biopsi pankreas', 'category' => 'Pankreas'],
            ['code' => '52.21', 'name' => 'Pankreatektomi', 'category' => 'Pankreas'],
            ['code' => '53.01', 'name' => 'Herniorafi inguinal', 'category' => 'Hernia'],
            ['code' => '53.21', 'name' => 'Repair hernia femoralis', 'category' => 'Hernia'],
            ['code' => '53.31', 'name' => 'Repair hernia umbilicalis', 'category' => 'Hernia'],
            ['code' => '54.11', 'name' => 'Laparotomi eksplorasi', 'category' => 'Abdomen'],
            ['code' => '54.21', 'name' => 'Laparoskopi diagnostik', 'category' => 'Abdomen'],
            ['code' => '54.31', 'name' => 'Biopsi dinding abdomen', 'category' => 'Abdomen'],
            ['code' => '55.01', 'name' => 'Nefrektomi', 'category' => 'Saluran Kemih'],
            ['code' => '55.11', 'name' => 'Biopsi ginjal', 'category' => 'Saluran Kemih'],
            ['code' => '55.31', 'name' => 'Sistoskopi', 'category' => 'Saluran Kemih'],
            ['code' => '55.41', 'name' => 'Ureteroskopi', 'category' => 'Saluran Kemih'],
            ['code' => '56.01', 'name' => 'TURP (reseksi prostat)', 'category' => 'Saluran Kemih'],
            ['code' => '56.11', 'name' => 'Biopsi prostat', 'category' => 'Saluran Kemih'],
            ['code' => '57.01', 'name' => 'Sistostomi', 'category' => 'Kandung Kemih'],
            ['code' => '57.21', 'name' => 'Sistektomi', 'category' => 'Kandung Kemih'],
            ['code' => '58.01', 'name' => 'Uretrotomi', 'category' => 'Uretra'],
            ['code' => '59.01', 'name' => 'Dilatasi uretra', 'category' => 'Uretra'],
            ['code' => '60.01', 'name' => 'Sirkumsisi', 'category' => 'Genital Pria'],
            ['code' => '60.11', 'name' => 'Orkiopeksi', 'category' => 'Genital Pria'],
            ['code' => '60.21', 'name' => 'Oriechtomi', 'category' => 'Genital Pria'],
            ['code' => '61.01', 'name' => 'Vasektomi', 'category' => 'Genital Pria'],
            ['code' => '61.21', 'name' => 'Reversi vasektomi', 'category' => 'Genital Pria'],
            ['code' => '62.01', 'name' => 'Hidroselektomi', 'category' => 'Genital Pria'],
            ['code' => '63.01', 'name' => 'Biopsi penis', 'category' => 'Genital Pria'],
            ['code' => '65.01', 'name' => 'Ooforektomi', 'category' => 'Genital Wanita'],
            ['code' => '65.11', 'name' => 'Kistektomi ovarium', 'category' => 'Genital Wanita'],
            ['code' => '66.01', 'name' => 'Salpingektomi', 'category' => 'Genital Wanita'],
            ['code' => '66.11', 'name' => 'Tubektomi (sterilisasi)', 'category' => 'Genital Wanita'],
            ['code' => '67.01', 'name' => 'Histerektomi', 'category' => 'Genital Wanita'],
            ['code' => '67.11', 'name' => 'Miomektomi', 'category' => 'Genital Wanita'],
            ['code' => '68.01', 'name' => 'D&C (kuretase)', 'category' => 'Genital Wanita'],
            ['code' => '68.11', 'name' => 'Kolposkopi', 'category' => 'Genital Wanita'],
            ['code' => '68.21', 'name' => 'Biopsi serviks', 'category' => 'Genital Wanita'],
            ['code' => '69.01', 'name' => 'Seksio sesarea', 'category' => 'Obstetri'],
            ['code' => '69.11', 'name' => 'Episiotomi', 'category' => 'Obstetri'],
            ['code' => '69.21', 'name' => 'Ekstraksi vakum', 'category' => 'Obstetri'],
            ['code' => '69.31', 'name' => 'Ekstraksi forsep', 'category' => 'Obstetri'],
            ['code' => '70.01', 'name' => 'Mammoplasti', 'category' => 'Payudara'],
            ['code' => '70.11', 'name' => 'Biopsi payudara', 'category' => 'Payudara'],
            ['code' => '70.21', 'name' => 'Mastektomi', 'category' => 'Payudara'],
            ['code' => '71.01', 'name' => 'Eksisi lesi kulit', 'category' => 'Kulit'],
            ['code' => '71.11', 'name' => 'Biopsi kulit', 'category' => 'Kulit'],
            ['code' => '71.21', 'name' => 'Cangkok kulit', 'category' => 'Kulit'],
            ['code' => '71.31', 'name' => 'Debridemen luka', 'category' => 'Kulit'],
            ['code' => '71.41', 'name' => 'Jahit luka', 'category' => 'Kulit'],
            ['code' => '72.11', 'name' => 'Fasiotomi', 'category' => 'Otot'],
            ['code' => '72.21', 'name' => 'Biopsi otot', 'category' => 'Otot'],
            ['code' => '72.31', 'name' => 'Amputasi jari', 'category' => 'Otot'],
            ['code' => '73.01', 'name' => 'Reduksi fraktur tertutup', 'category' => 'Tulang'],
            ['code' => '73.11', 'name' => 'ORIF (open reduction)', 'category' => 'Tulang'],
            ['code' => '73.21', 'name' => 'Fiksasi eksternal', 'category' => 'Tulang'],
            ['code' => '73.31', 'name' => 'Operasi pinggul (THR)', 'category' => 'Tulang'],
            ['code' => '73.41', 'name' => 'Operasi lutut (TKR)', 'category' => 'Tulang'],
            ['code' => '73.51', 'name' => 'Operasi bahu', 'category' => 'Tulang'],
            ['code' => '74.01', 'name' => 'Artroskopi', 'category' => 'Tulang'],
            ['code' => '74.11', 'name' => 'Aspirasi sendi', 'category' => 'Tulang'],
            ['code' => '74.21', 'name' => 'Fusi spinal', 'category' => 'Tulang Belakang'],
            ['code' => '74.31', 'name' => 'Laminektomi', 'category' => 'Tulang Belakang'],
            ['code' => '74.41', 'name' => 'Diskektomi', 'category' => 'Tulang Belakang'],
            ['code' => '75.01', 'name' => 'Biopsi tulang', 'category' => 'Tulang'],
            ['code' => '75.11', 'name' => 'Cangkok tulang', 'category' => 'Tulang'],
            ['code' => '76.01', 'name' => 'Pasang gips', 'category' => 'Tulang'],
            ['code' => '77.01', 'name' => 'Pemeriksaan fisik umum', 'category' => 'Umum'],
            ['code' => '77.11', 'name' => 'Imunisasi', 'category' => 'Umum'],
            ['code' => '77.21', 'name' => 'Transfusi darah', 'category' => 'Umum'],
            ['code' => '77.31', 'name' => 'Dialisis', 'category' => 'Umum'],
            ['code' => '77.41', 'name' => 'Foto toraks', 'category' => 'Radiologi'],
            ['code' => '77.51', 'name' => 'CT scan kepala', 'category' => 'Radiologi'],
            ['code' => '77.61', 'name' => 'MRI otak', 'category' => 'Radiologi'],
            ['code' => '77.71', 'name' => 'USG abdomen', 'category' => 'Radiologi'],
            ['code' => '77.81', 'name' => 'EKG', 'category' => 'Radiologi'],
            ['code' => '77.91', 'name' => 'Ekokardiogram', 'category' => 'Radiologi'],
            ['code' => '78.01', 'name' => 'EEG (rekam gelombang otak)', 'category' => 'Neurodiagnostik'],
            ['code' => '78.11', 'name' => 'EMG (hantar saraf)', 'category' => 'Neurodiagnostik'],
            ['code' => '78.21', 'name' => 'Tes fungsi paru', 'category' => 'Pulmonologi'],
            ['code' => '78.31', 'name' => 'Analisis gas darah', 'category' => 'Laboratorium'],
            ['code' => '78.41', 'name' => 'Tes alergi', 'category' => 'Laboratorium'],
        ];

        DB::table('icd9_cm_diagnoses')->insert($procedures);
    }

    public function down(): void
    {
        DB::table('icd9_cm_diagnoses')->truncate();
    }
};
