<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $diagnoses = [
            ['code' => 'A09', 'name' => 'Diare dan gastroenteritis', 'category' => 'Infeksi', 'is_active' => true],
            ['code' => 'A15', 'name' => 'Tuberkulosis paru', 'category' => 'Infeksi', 'is_active' => true],
            ['code' => 'A90', 'name' => 'Demam dengue', 'category' => 'Infeksi', 'is_active' => true],
            ['code' => 'B00', 'name' => 'Infeksi herpes', 'category' => 'Infeksi', 'is_active' => true],
            ['code' => 'B01', 'name' => 'Varicella (cacar air)', 'category' => 'Infeksi', 'is_active' => true],
            ['code' => 'B02', 'name' => 'Herpes zoster', 'category' => 'Infeksi', 'is_active' => true],
            ['code' => 'B05', 'name' => 'Campak', 'category' => 'Infeksi', 'is_active' => true],
            ['code' => 'B15', 'name' => 'Hepatitis A akut', 'category' => 'Infeksi', 'is_active' => true],
            ['code' => 'B16', 'name' => 'Hepatitis B akut', 'category' => 'Infeksi', 'is_active' => true],
            ['code' => 'B18', 'name' => 'Hepatitis B kronis', 'category' => 'Infeksi', 'is_active' => true],
            ['code' => 'B20', 'name' => 'Penyakit HIV', 'category' => 'Infeksi', 'is_active' => true],
            ['code' => 'B24', 'name' => 'HIV/AIDS tidak ditentukan', 'category' => 'Infeksi', 'is_active' => true],
            ['code' => 'B37', 'name' => 'Kandidiasis', 'category' => 'Infeksi', 'is_active' => true],
            ['code' => 'B54', 'name' => 'Malaria', 'category' => 'Infeksi', 'is_active' => true],
            ['code' => 'B86', 'name' => 'Skabies', 'category' => 'Infeksi', 'is_active' => true],
            ['code' => 'C16', 'name' => 'Karsinoma lambung', 'category' => 'Neoplasma', 'is_active' => true],
            ['code' => 'C18', 'name' => 'Karsinoma kolon', 'category' => 'Neoplasma', 'is_active' => true],
            ['code' => 'C20', 'name' => 'Karsinoma rektum', 'category' => 'Neoplasma', 'is_active' => true],
            ['code' => 'C22', 'name' => 'Karsinoma hati', 'category' => 'Neoplasma', 'is_active' => true],
            ['code' => 'C34', 'name' => 'Karsinoma paru', 'category' => 'Neoplasma', 'is_active' => true],
            ['code' => 'C50', 'name' => 'Karsinoma payudara', 'category' => 'Neoplasma', 'is_active' => true],
            ['code' => 'C53', 'name' => 'Karsinoma serviks', 'category' => 'Neoplasma', 'is_active' => true],
            ['code' => 'C61', 'name' => 'Karsinoma prostat', 'category' => 'Neoplasma', 'is_active' => true],
            ['code' => 'C64', 'name' => 'Karsinoma ginjal', 'category' => 'Neoplasma', 'is_active' => true],
            ['code' => 'C67', 'name' => 'Karsinoma kandung kemih', 'category' => 'Neoplasma', 'is_active' => true],
            ['code' => 'C91', 'name' => 'Leukemia limfoid', 'category' => 'Neoplasma', 'is_active' => true],
            ['code' => 'C92', 'name' => 'Leukemia mieloid', 'category' => 'Neoplasma', 'is_active' => true],
            ['code' => 'D12', 'name' => 'Polip kolon jinak', 'category' => 'Neoplasma', 'is_active' => true],
            ['code' => 'D25', 'name' => 'Mioma uteri', 'category' => 'Neoplasma', 'is_active' => true],
            ['code' => 'D27', 'name' => 'Kista ovarium jinak', 'category' => 'Neoplasma', 'is_active' => true],
            ['code' => 'D50', 'name' => 'Anemia defisiensi besi', 'category' => 'Penyakit Darah', 'is_active' => true],
            ['code' => 'D56', 'name' => 'Thalassemia', 'category' => 'Penyakit Darah', 'is_active' => true],
            ['code' => 'D64', 'name' => 'Anemia tidak ditentukan', 'category' => 'Penyakit Darah', 'is_active' => true],
            ['code' => 'E03', 'name' => 'Hipotiroidisme', 'category' => 'Endokrin', 'is_active' => true],
            ['code' => 'E05', 'name' => 'Hipertiroidisme', 'category' => 'Endokrin', 'is_active' => true],
            ['code' => 'E10', 'name' => 'Diabetes melitus tipe 1', 'category' => 'Endokrin', 'is_active' => true],
            ['code' => 'E11', 'name' => 'Diabetes melitus tipe 2', 'category' => 'Endokrin', 'is_active' => true],
            ['code' => 'E14', 'name' => 'Diabetes melitus tidak ditentukan', 'category' => 'Endokrin', 'is_active' => true],
            ['code' => 'E66', 'name' => 'Obesitas', 'category' => 'Endokrin', 'is_active' => true],
            ['code' => 'E78', 'name' => 'Hiperlipidemia', 'category' => 'Endokrin', 'is_active' => true],
            ['code' => 'E86', 'name' => 'Dehidrasi', 'category' => 'Endokrin', 'is_active' => true],
            ['code' => 'F10', 'name' => 'Gangguan akibat alkohol', 'category' => 'Mental', 'is_active' => true],
            ['code' => 'F17', 'name' => 'Gangguan akibat tembakau', 'category' => 'Mental', 'is_active' => true],
            ['code' => 'F20', 'name' => 'Skizofrenia', 'category' => 'Mental', 'is_active' => true],
            ['code' => 'F31', 'name' => 'Gangguan bipolar', 'category' => 'Mental', 'is_active' => true],
            ['code' => 'F32', 'name' => 'Depresi', 'category' => 'Mental', 'is_active' => true],
            ['code' => 'F41', 'name' => 'Gangguan kecemasan', 'category' => 'Mental', 'is_active' => true],
            ['code' => 'F48', 'name' => 'Gangguan neurotik', 'category' => 'Mental', 'is_active' => true],
            ['code' => 'G20', 'name' => 'Penyakit Parkinson', 'category' => 'Saraf', 'is_active' => true],
            ['code' => 'G30', 'name' => 'Penyakit Alzheimer', 'category' => 'Saraf', 'is_active' => true],
            ['code' => 'G40', 'name' => 'Epilepsi', 'category' => 'Saraf', 'is_active' => true],
            ['code' => 'G43', 'name' => 'Migren', 'category' => 'Saraf', 'is_active' => true],
            ['code' => 'G44', 'name' => 'Sakit kepala tegang', 'category' => 'Saraf', 'is_active' => true],
            ['code' => 'G45', 'name' => 'TIA', 'category' => 'Saraf', 'is_active' => true],
            ['code' => 'G47', 'name' => 'Insomnia', 'category' => 'Saraf', 'is_active' => true],
            ['code' => 'G51', 'name' => 'Bell palsy', 'category' => 'Saraf', 'is_active' => true],
            ['code' => 'G56', 'name' => 'Carpal tunnel syndrome', 'category' => 'Saraf', 'is_active' => true],
            ['code' => 'H10', 'name' => 'Konjungtivitis', 'category' => 'Mata', 'is_active' => true],
            ['code' => 'H25', 'name' => 'Katarak', 'category' => 'Mata', 'is_active' => true],
            ['code' => 'H40', 'name' => 'Glaukoma', 'category' => 'Mata', 'is_active' => true],
            ['code' => 'H52', 'name' => 'Gangguan refraksi', 'category' => 'Mata', 'is_active' => true],
            ['code' => 'H54', 'name' => 'Kebutaan', 'category' => 'Mata', 'is_active' => true],
            ['code' => 'H60', 'name' => 'Otitis eksterna', 'category' => 'Telinga', 'is_active' => true],
            ['code' => 'H65', 'name' => 'Otitis media', 'category' => 'Telinga', 'is_active' => true],
            ['code' => 'H66', 'name' => 'Otitis media supuratif', 'category' => 'Telinga', 'is_active' => true],
            ['code' => 'H81', 'name' => 'Vertigo', 'category' => 'Telinga', 'is_active' => true],
            ['code' => 'H90', 'name' => 'Gangguan pendengaran', 'category' => 'Telinga', 'is_active' => true],
            ['code' => 'I10', 'name' => 'Hipertensi primer', 'category' => 'Kardiovaskular', 'is_active' => true],
            ['code' => 'I11', 'name' => 'Penyakit jantung hipertensi', 'category' => 'Kardiovaskular', 'is_active' => true],
            ['code' => 'I20', 'name' => 'Angina pektoris', 'category' => 'Kardiovaskular', 'is_active' => true],
            ['code' => 'I21', 'name' => 'Infark miokard akut', 'category' => 'Kardiovaskular', 'is_active' => true],
            ['code' => 'I25', 'name' => 'PJK kronis', 'category' => 'Kardiovaskular', 'is_active' => true],
            ['code' => 'I26', 'name' => 'Emboli paru', 'category' => 'Kardiovaskular', 'is_active' => true],
            ['code' => 'I42', 'name' => 'Kardiomiopati', 'category' => 'Kardiovaskular', 'is_active' => true],
            ['code' => 'I48', 'name' => 'Fibrilasi atrium', 'category' => 'Kardiovaskular', 'is_active' => true],
            ['code' => 'I49', 'name' => 'Aritmia', 'category' => 'Kardiovaskular', 'is_active' => true],
            ['code' => 'I50', 'name' => 'Gagal jantung', 'category' => 'Kardiovaskular', 'is_active' => true],
            ['code' => 'I61', 'name' => 'Perdarahan intraserebral', 'category' => 'Kardiovaskular', 'is_active' => true],
            ['code' => 'I63', 'name' => 'Infark serebral (stroke)', 'category' => 'Kardiovaskular', 'is_active' => true],
            ['code' => 'I64', 'name' => 'Stroke tidak ditentukan', 'category' => 'Kardiovaskular', 'is_active' => true],
            ['code' => 'I70', 'name' => 'Aterosklerosis', 'category' => 'Kardiovaskular', 'is_active' => true],
            ['code' => 'I83', 'name' => 'Varises ekstremitas bawah', 'category' => 'Kardiovaskular', 'is_active' => true],
            ['code' => 'I84', 'name' => 'Wasir', 'category' => 'Kardiovaskular', 'is_active' => true],
            ['code' => 'I95', 'name' => 'Hipotensi', 'category' => 'Kardiovaskular', 'is_active' => true],
            ['code' => 'J00', 'name' => 'Pilek biasa', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'J01', 'name' => 'Sinusitis akut', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'J02', 'name' => 'Faringitis akut', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'J03', 'name' => 'Tonsilitis akut', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'J04', 'name' => 'Laringitis akut', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'J06', 'name' => 'ISPA akut', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'J10', 'name' => 'Influenza', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'J15', 'name' => 'Pneumonia bakteri', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'J18', 'name' => 'Pneumonia', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'J20', 'name' => 'Bronkitis akut', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'J30', 'name' => 'Rinitis alergi', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'J32', 'name' => 'Sinusitis kronis', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'J34', 'name' => 'Deviasi septum nasi', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'J35', 'name' => 'Hipertrofi tonsil', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'J40', 'name' => 'Bronkitis', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'J43', 'name' => 'Emfisema', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'J44', 'name' => 'PPOK', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'J45', 'name' => 'Asma', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'J80', 'name' => 'ARDS', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'J81', 'name' => 'Edema paru', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'J84', 'name' => 'Fibrosis paru', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'J93', 'name' => 'Pneumotoraks', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'J96', 'name' => 'Gagal napas', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'J98', 'name' => 'Penyakit napas lain', 'category' => 'Napas', 'is_active' => true],
            ['code' => 'K02', 'name' => 'Karies gigi', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K04', 'name' => 'Pulpitis', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K05', 'name' => 'Gingivitis', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K07', 'name' => 'Gangguan rahang', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K08', 'name' => 'Gangguan mulut lain', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K20', 'name' => 'Esofagitis', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K21', 'name' => 'GERD', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K25', 'name' => 'Ulkus peptikum', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K26', 'name' => 'Ulkus duodenum', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K29', 'name' => 'Gastritis', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K30', 'name' => 'Dispepsia', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K31', 'name' => 'Penyakit lambung lain', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K35', 'name' => 'Apendisitis akut', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K36', 'name' => 'Apendisitis lain', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K40', 'name' => 'Hernia inguinalis', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K42', 'name' => 'Hernia umbilicalis', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K44', 'name' => 'Hernia diafragma', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K50', 'name' => 'Crohn disease', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K51', 'name' => 'Kolitis ulseratif', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K52', 'name' => 'Gastroenteritis non-infeksi', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K56', 'name' => 'Ileus paralitik', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K57', 'name' => 'Divertikulosis', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K59', 'name' => 'Konstipasi', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K60', 'name' => 'Fisura ani', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K61', 'name' => 'Abses anorektal', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K62', 'name' => 'Penyakit anus lain', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K63', 'name' => 'Penyakit usus lain', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K70', 'name' => 'Penyakit hati alkoholik', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K71', 'name' => 'Penyakit hati toksik', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K72', 'name' => 'Gagal hati', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K73', 'name' => 'Hepatitis kronis', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K74', 'name' => 'Fibrosis/sirosis hati', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K75', 'name' => 'Penyakit hati inflamasi', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K76', 'name' => 'Penyakit hati lain', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K80', 'name' => 'Kolelitiasis', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K81', 'name' => 'Kolesistitis', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K82', 'name' => 'Penyakit kandung empedu lain', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K85', 'name' => 'Pankreatitis akut', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K86', 'name' => 'Pankreatitis kronis', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K90', 'name' => 'Malabsorpsi', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'K92', 'name' => 'Perdarahan saluran cerna', 'category' => 'Pencernaan', 'is_active' => true],
            ['code' => 'L00', 'name' => 'Impetigo', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L01', 'name' => 'Selulitis', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L02', 'name' => 'Abses kulit', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L03', 'name' => 'Selulitis akut', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L04', 'name' => 'Limfadenitis akut', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L05', 'name' => 'Kista pilonidal', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L08', 'name' => 'Infeksi kulit lokal', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L20', 'name' => 'Dermatitis atopik', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L21', 'name' => 'Dermatitis seboroik', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L23', 'name' => 'Dermatitis alergi', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L24', 'name' => 'Dermatitis iritan', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L25', 'name' => 'Dermatitis kontak', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L27', 'name' => 'Ruam obat', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L29', 'name' => 'Pruritus', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L30', 'name' => 'Dermatitis lain', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L40', 'name' => 'Psoriasis', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L50', 'name' => 'Urtikaria', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L60', 'name' => 'Gangguan kuku', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L70', 'name' => 'Akne', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L80', 'name' => 'Vitiligo', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L81', 'name' => 'Gangguan pigmentasi', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L89', 'name' => 'Ulkus dekubitus', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L91', 'name' => 'Jaringan parut', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L92', 'name' => 'Granuloma kulit', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L93', 'name' => 'Lupus eritematosus', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L97', 'name' => 'Ulkus tungkai', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'L98', 'name' => 'Penyakit kulit lain', 'category' => 'Kulit', 'is_active' => true],
            ['code' => 'M00', 'name' => 'Artritis piogenik', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M05', 'name' => 'RA seropositif', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M06', 'name' => 'RA seronegatif', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M10', 'name' => 'Gout', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M13', 'name' => 'Artritis lain', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M15', 'name' => 'Osteoartritis generalisata', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M16', 'name' => 'OA panggul', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M17', 'name' => 'OA lutut', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M19', 'name' => 'OA lain', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M20', 'name' => 'Hallux valgus', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M23', 'name' => 'Gangguan meniskus', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M24', 'name' => 'Gangguan sendi lain', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M25', 'name' => 'Nyeri sendi', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M32', 'name' => 'SLE', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M35', 'name' => 'Sindrom Sjogren', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M40', 'name' => 'Kifosis', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M41', 'name' => 'Skoliosis', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M42', 'name' => 'Osteokondrosis', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M43', 'name' => 'Gangguan tulang belakang lain', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M45', 'name' => 'Ankylosing spondylitis', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M47', 'name' => 'Spondilosis', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M48', 'name' => 'Stenosis spinal', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M50', 'name' => 'HNP servikal', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M51', 'name' => 'HNP lumbal', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M53', 'name' => 'Gangguan tulang belakang lain', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M54', 'name' => 'Punggung nyeri', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M60', 'name' => 'Miositis', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M62', 'name' => 'Gangguan otot', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M65', 'name' => 'Tenosinovitis', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M66', 'name' => 'Ruptur tendon', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M67', 'name' => 'Gangguan tendon lain', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M70', 'name' => 'Gangguan jaringan lunak', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M71', 'name' => 'Bursitis', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M72', 'name' => 'Fibromatosis', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M75', 'name' => 'Lesi bahu', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M76', 'name' => 'Entesopati ekstremitas bawah', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M77', 'name' => 'Entesopati lain', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M79', 'name' => 'Nyeri muskuloskeletal', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M80', 'name' => 'Osteoporosis patologis', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M81', 'name' => 'Osteoporosis', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M84', 'name' => 'Fraktur patologis', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M85', 'name' => 'Gangguan densitas tulang', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M86', 'name' => 'Osteomielitis', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M87', 'name' => 'Osteonekrosis', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M89', 'name' => 'Gangguan tulang lain', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M94', 'name' => 'Gangguan tulang rawan', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M95', 'name' => 'Deformitas MSK lain', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'M99', 'name' => 'Lesi biomekanis', 'category' => 'Muskuloskeletal', 'is_active' => true],
            ['code' => 'N00', 'name' => 'Sindrom nefritik akut', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N01', 'name' => 'GN progresif cepat', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N02', 'name' => 'Hematuria rekuren', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N03', 'name' => 'Sindrom nefritik kronis', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N04', 'name' => 'Sindrom nefrotik', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N05', 'name' => 'Sindrom nefritik tidak ditentukan', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N10', 'name' => 'Pielonefritis akut', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N11', 'name' => 'Pielonefritis kronis', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N12', 'name' => 'Nefritis tubulointerstitial', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N13', 'name' => 'Uropati obstruktif', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N15', 'name' => 'Penyakit ginjal tubulointerstitial lain', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N17', 'name' => 'Gagal ginjal akut', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N18', 'name' => 'PGK', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N19', 'name' => 'Gagal ginjal tidak ditentukan', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N20', 'name' => 'Batu ginjal dan ureter', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N21', 'name' => 'Batu saluran kemih bawah', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N23', 'name' => 'Kolik renal', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N28', 'name' => 'Penyakit ginjal lain', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N30', 'name' => 'Sistitis', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N31', 'name' => 'Gangguan fungsi kandung kemih', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N32', 'name' => 'Gangguan kandung kemih lain', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N34', 'name' => 'Uretritis', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N35', 'name' => 'Striktur uretra', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N39', 'name' => 'ISK', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N40', 'name' => 'BPH', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N41', 'name' => 'Prostatitis', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N42', 'name' => 'Gangguan prostat lain', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N43', 'name' => 'Hidrokel', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N45', 'name' => 'Orkitis', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N47', 'name' => 'Fimosis', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N48', 'name' => 'Gangguan penis', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N49', 'name' => 'Gangguan genital pria lain', 'category' => 'Ginjal', 'is_active' => true],
            ['code' => 'N60', 'name' => 'Kista payudara jinak', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N61', 'name' => 'Mastitis', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N62', 'name' => 'Hipertrofi payudara', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N63', 'name' => 'Benjolan payudara', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N64', 'name' => 'Gangguan payudara lain', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N70', 'name' => 'Salpingitis', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N71', 'name' => 'Penyakit inflamasi uterus', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N72', 'name' => 'Servisitis', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N73', 'name' => 'PID lain', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N75', 'name' => 'Kista Bartholin', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N76', 'name' => 'Vaginitis', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N80', 'name' => 'Endometriosis', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N81', 'name' => 'Prolaps genital', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N82', 'name' => 'Fistula genital', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N83', 'name' => 'Kista ovarium', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N84', 'name' => 'Polip genital', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N85', 'name' => 'Gangguan uterus lain', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N87', 'name' => 'Displasia serviks', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N88', 'name' => 'Gangguan serviks lain', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N89', 'name' => 'Gangguan vagina lain', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N90', 'name' => 'Gangguan vulva lain', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N91', 'name' => 'Amenore', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N92', 'name' => 'Menoragia', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N93', 'name' => 'Perdarahan uterus abnormal', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N94', 'name' => 'Nyeri haid', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N95', 'name' => 'Menopause', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'N97', 'name' => 'Infertilitas', 'category' => 'Reproduksi', 'is_active' => true],
            ['code' => 'O00', 'name' => 'Kehamilan ektopik', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O01', 'name' => 'Mola hidatidosa', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O02', 'name' => 'Abortus', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O03', 'name' => 'Abortus spontan', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O04', 'name' => 'Abortus medis', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O10', 'name' => 'Hipertensi pada kehamilan', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O11', 'name' => 'Preeklampsia', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O12', 'name' => 'Edema kehamilan', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O13', 'name' => 'Hipertensi gestasional', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O14', 'name' => 'Preeklampsia berat', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O15', 'name' => 'Eklampsia', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O20', 'name' => 'Perdarahan awal kehamilan', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O21', 'name' => 'Hiperemesis gravidarum', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O24', 'name' => 'DM gestasional', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O26', 'name' => 'Perawatan ibu hamil', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O30', 'name' => 'Kehamilan ganda', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O32', 'name' => 'Malpresentasi', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O34', 'name' => 'Caretaking pelvis', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O36', 'name' => 'Perawatan ibu janin', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O41', 'name' => 'Ketuban pecah dini', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O42', 'name' => 'KPD', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O44', 'name' => 'Plasenta previa', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O45', 'name' => 'Solusio plasenta', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O46', 'name' => 'Perdarahan antepartum', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O47', 'name' => 'Kontraksi palsu', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O48', 'name' => 'Kehamilan lewat waktu', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O60', 'name' => 'Persalinan preterm', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O61', 'name' => 'Induksi persalinan', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O62', 'name' => 'Kelainan his', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O63', 'name' => 'Persalinan lama', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O64', 'name' => 'Obstruksi persalinan', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O65', 'name' => 'Disproporsi', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O66', 'name' => 'Obstruksi lain', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O68', 'name' => 'Gawat janin', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O69', 'name' => 'Komplikasi tali pusat', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O70', 'name' => 'Robekan perineum', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O71', 'name' => 'Trauma obstetri', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O72', 'name' => 'Perdarahan postpartum', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O73', 'name' => 'Retensi plasenta', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O74', 'name' => 'Komplikasi anestesi', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O75', 'name' => 'Komplikasi persalinan lain', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O80', 'name' => 'Persalinan normal', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O81', 'name' => 'Persalinan dengan forsep', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O82', 'name' => 'SC', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O85', 'name' => 'Infeksi nifas', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O86', 'name' => 'Infeksi postpartum lain', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O87', 'name' => 'Trombosis vena nifas', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O88', 'name' => 'Emboli obstetri', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O89', 'name' => 'Komplikasi nifas lain', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O90', 'name' => 'Komplikasi nifas lain', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O91', 'name' => 'Mastitis nifas', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O92', 'name' => 'Gangguan laktasi', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O95', 'name' => 'Kematian ibu', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O98', 'name' => 'Penyakit ibu hamil', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'O99', 'name' => 'Kondisi ibu hamil lain', 'category' => 'Kebidanan', 'is_active' => true],
            ['code' => 'P00', 'name' => 'Pengaruh kondisi ibu pada bayi', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P01', 'name' => 'Pengaruh komplikasi ibu', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P02', 'name' => 'Pengaruh komplikasi plasenta', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P03', 'name' => 'Pengaruh komplikasi persalinan', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P05', 'name' => 'Pertumbuhan janin lambat', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P07', 'name' => 'BBLR', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P08', 'name' => 'Bayi besar', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P10', 'name' => 'Trauma lahir intrakranial', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P11', 'name' => 'Trauma lahir SSP', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P12', 'name' => 'Trauma lahir kulit kepala', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P13', 'name' => 'Trauma lahir skeletal', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P14', 'name' => 'Trauma lahir saraf perifer', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P15', 'name' => 'Trauma lahir lain', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P20', 'name' => 'Hipoksia intrauterin', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P21', 'name' => 'Asfiksia lahir', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P22', 'name' => 'Gangguan napas neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P23', 'name' => 'Pneumonia kongenital', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P24', 'name' => 'Aspirasi neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P25', 'name' => 'Emfisema interstisial', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P26', 'name' => 'Perdarahan paru neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P27', 'name' => 'Penyakit paru kronis neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P28', 'name' => 'Gangguan napas neonatus lain', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P29', 'name' => 'Gangguan kardiovaskular neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P35', 'name' => 'Infeksi kongenital', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P36', 'name' => 'Sepsis neonatorum', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P37', 'name' => 'Infeksi kongenital lain', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P38', 'name' => 'Omfalitis', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P39', 'name' => 'Infeksi neonatus lain', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P50', 'name' => 'Hilang darah janin', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P51', 'name' => 'Perdarahan tali pusat', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P52', 'name' => 'Perdarahan intrakranial neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P53', 'name' => 'DIC neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P54', 'name' => 'Perdarahan neonatus lain', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P55', 'name' => 'Penyakit hemolitik neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P56', 'name' => 'Hidrops fetalis', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P57', 'name' => 'Kernikterus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P58', 'name' => 'Ikterus neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P59', 'name' => 'Ikterus neonatus lain', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P60', 'name' => 'Koagulasi DIC', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P61', 'name' => 'Gangguan hematologi neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P70', 'name' => 'Gangguan metabolik neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P71', 'name' => 'Hipokalsemia neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P72', 'name' => 'Gangguan endokrin neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P74', 'name' => 'Gangguan elektrolit neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P75', 'name' => 'Mekonium ileus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P76', 'name' => 'Obstruksi usus neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P77', 'name' => 'NEC', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P78', 'name' => 'Gangguan pencernaan neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P80', 'name' => 'Hipotermia neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P81', 'name' => 'Gangguan suhu neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P83', 'name' => 'Kondisi kulit neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P90', 'name' => 'Kejang neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P91', 'name' => 'Gangguan SSP neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P92', 'name' => 'Masalah makan neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P93', 'name' => 'Reaksi obat neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P94', 'name' => 'Gangguan tonus neonatus', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P95', 'name' => 'Lahir mati', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'P96', 'name' => 'Kondisi neonatus lain', 'category' => 'Neonatal', 'is_active' => true],
            ['code' => 'R00', 'name' => 'Palpitasi', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R01', 'name' => 'Bising jantung', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R02', 'name' => 'Gangren', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R03', 'name' => 'Tekanan darah abnormal', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R04', 'name' => 'Perdarahan saluran napas', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R05', 'name' => 'Batuk', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R06', 'name' => 'Sesak napas', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R07', 'name' => 'Nyeri tenggorokan/dada', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R08', 'name' => 'Mual muntah', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R09', 'name' => 'Gejala sistem napas lain', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R10', 'name' => 'Nyeri perut', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R11', 'name' => 'Mual dan muntah', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R12', 'name' => 'Heartburn', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R13', 'name' => 'Disfagia', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R14', 'name' => 'Perut kembung', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R15', 'name' => 'Inkontinensia feses', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R16', 'name' => 'Hepatomegali', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R17', 'name' => 'Ikterus', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R18', 'name' => 'Asites', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R19', 'name' => 'Gejala pencernaan lain', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R20', 'name' => 'Gangguan sensasi kulit', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R21', 'name' => 'Ruam kulit', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R22', 'name' => 'Benjolan kulit', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R23', 'name' => 'Perubahan kulit lain', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R25', 'name' => 'Gerakan abnormal', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R26', 'name' => 'Gangguan jalan', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R27', 'name' => 'Ataksia', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R29', 'name' => 'Gejala saraf lain', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R30', 'name' => 'Nyeri saat kencing', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R31', 'name' => 'Hematuria', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R32', 'name' => 'Inkontinensia urin', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R33', 'name' => 'Retensi urin', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R34', 'name' => 'Anuria', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R35', 'name' => 'Poliuria', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R36', 'name' => 'Disuria', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R39', 'name' => 'Gejala urinari lain', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R40', 'name' => 'Somnolen', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R41', 'name' => 'Gejala kognitif', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R42', 'name' => 'Pusing', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R43', 'name' => 'Gangguan penciuman', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R44', 'name' => 'Halusinasi', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R45', 'name' => 'Gejala emosional', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R46', 'name' => 'Gejala penampilan', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R47', 'name' => 'Gangguan bicara', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R48', 'name' => 'Gangguan belajar', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R49', 'name' => 'Gangguan suara', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R50', 'name' => 'Demam', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R51', 'name' => 'Sakit kepala', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R52', 'name' => 'Nyeri kronis', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R53', 'name' => 'Lemah lesu', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R54', 'name' => 'Usia lanjut', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R55', 'name' => 'Pingsan', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R56', 'name' => 'Kejang', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R57', 'name' => 'Syok', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R58', 'name' => 'Perdarahan', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R59', 'name' => 'Pembesaran kelenjar', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R60', 'name' => 'Edema', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R61', 'name' => 'Hiperhidrosis', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R62', 'name' => 'Keterlambatan tumbuh', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R63', 'name' => 'Gejala makan/minum', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R64', 'name' => 'Kakeksia', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R68', 'name' => 'Gejala umum lain', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R69', 'name' => 'Penyebab tidak diketahui', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R70', 'name' => 'LED meningkat', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R71', 'name' => 'Kelainan SDM', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R72', 'name' => 'Kelainan SDP', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R73', 'name' => 'GDS meningkat', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R74', 'name' => 'Enzim abnormal', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R75', 'name' => 'Tes HIV positif', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R76', 'name' => 'Tes serologi abnormal', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R77', 'name' => 'Protein plasma abnormal', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R78', 'name' => 'Obat dalam darah', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R79', 'name' => 'Kimia darah abnormal', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R80', 'name' => 'Proteinuria', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R81', 'name' => 'Glukosuria', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R82', 'name' => 'Urinalisis abnormal', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R83', 'name' => 'CSF abnormal', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R84', 'name' => 'Hasil napas abnormal', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R85', 'name' => 'Hasil pencernaan abnormal', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R86', 'name' => 'Hasil genital pria abnormal', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R87', 'name' => 'Hasil genital wanita abnormal', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R89', 'name' => 'Hasil pemeriksaan lain', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R90', 'name' => 'Hasil CT scan abnormal', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R91', 'name' => 'Hasil X-ray paru', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R92', 'name' => 'Mamografi abnormal', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R93', 'name' => 'Hasil imaging lain', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R94', 'name' => 'Hasil fungsi abnormal', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R95', 'name' => 'SIDS', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R96', 'name' => 'Kematian mendadak', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R98', 'name' => 'Kematian tanpa saksi', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'R99', 'name' => 'Penyebab kematian tidak diketahui', 'category' => 'Gejala', 'is_active' => true],
            ['code' => 'S00', 'name' => 'Cedera kepala superfisial', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S01', 'name' => 'Luka terbuka kepala', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S02', 'name' => 'Fraktur tulang tengkorak', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S03', 'name' => 'Dislokasi sendi kepala', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S04', 'name' => 'Cedera saraf kranial', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S05', 'name' => 'Cedera mata', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S06', 'name' => 'Cedera intrakranial', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S07', 'name' => 'Cedera remuk kepala', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S08', 'name' => 'Avulsi kepala', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S09', 'name' => 'Cedera kepala lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S10', 'name' => 'Cedera leher superfisial', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S11', 'name' => 'Luka terbuka leher', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S12', 'name' => 'Fraktur vertebra servikal', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S13', 'name' => 'Dislokasi leher', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S14', 'name' => 'Cedera saraf leher', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S15', 'name' => 'Cedera pembuluh leher', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S16', 'name' => 'Cedera otot leher', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S17', 'name' => 'Cedera remuk leher', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S18', 'name' => 'Amputasi leher', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S19', 'name' => 'Cedera leher lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S20', 'name' => 'Cedera dada superfisial', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S21', 'name' => 'Luka terbuka dada', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S22', 'name' => 'Fraktur iga/tulang dada', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S23', 'name' => 'Dislokasi toraks', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S24', 'name' => 'Cedera saraf toraks', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S25', 'name' => 'Cedera pembuluh toraks', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S26', 'name' => 'Cedera jantung', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S27', 'name' => 'Cedera organ toraks lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S28', 'name' => 'Cedera remuk dada', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S29', 'name' => 'Cedera dada lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S30', 'name' => 'Cedera abdomen bawah superfisial', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S31', 'name' => 'Luka terbuka abdomen', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S32', 'name' => 'Fraktur vertebra lumbal/panggul', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S33', 'name' => 'Dislokasi lumbal/panggul', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S34', 'name' => 'Cedera saraf lumbal', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S35', 'name' => 'Cedera pembuluh abdomen', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S36', 'name' => 'Cedera organ abdomen', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S37', 'name' => 'Cedera organ panggul', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S38', 'name' => 'Cedera remuk abdomen', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S39', 'name' => 'Cedera abdomen lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S40', 'name' => 'Cedera bahu/lengan superfisial', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S41', 'name' => 'Luka terbuka bahu/lengan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S42', 'name' => 'Fraktur bahu/lengan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S43', 'name' => 'Dislokasi bahu', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S44', 'name' => 'Cedera saraf bahu/lengan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S45', 'name' => 'Cedera pembuluh bahu/lengan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S46', 'name' => 'Cedera otot bahu/lengan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S47', 'name' => 'Cedera remuk bahu/lengan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S48', 'name' => 'Amputasi bahu/lengan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S49', 'name' => 'Cedera bahu/lengan lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S50', 'name' => 'Cedera lengan bawah superfisial', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S51', 'name' => 'Luka terbuka lengan bawah', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S52', 'name' => 'Fraktur lengan bawah', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S53', 'name' => 'Dislokasi siku', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S54', 'name' => 'Cedera saraf lengan bawah', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S55', 'name' => 'Cedera pembuluh lengan bawah', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S56', 'name' => 'Cedera otot lengan bawah', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S57', 'name' => 'Cedera remuk lengan bawah', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S58', 'name' => 'Amputasi lengan bawah', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S59', 'name' => 'Cedera lengan bawah lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S60', 'name' => 'Cedera pergelangan/tangan superfisial', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S61', 'name' => 'Luka terbuka pergelangan/tangan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S62', 'name' => 'Fraktur pergelangan/tangan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S63', 'name' => 'Dislokasi pergelangan/tangan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S64', 'name' => 'Cedera saraf tangan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S65', 'name' => 'Cedera pembuluh tangan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S66', 'name' => 'Cedera otot tangan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S67', 'name' => 'Cedera remuk tangan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S68', 'name' => 'Amputasi tangan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S69', 'name' => 'Cedera tangan lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S70', 'name' => 'Cedera pinggul/paha superfisial', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S71', 'name' => 'Luka terbuka pinggul/paha', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S72', 'name' => 'Fraktur femur', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S73', 'name' => 'Dislokasi pinggul', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S74', 'name' => 'Cedera saraf pinggul/paha', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S75', 'name' => 'Cedera pembuluh pinggul/paha', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S76', 'name' => 'Cedera otot pinggul/paha', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S77', 'name' => 'Cedera remuk pinggul/paha', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S78', 'name' => 'Amputasi pinggul/paha', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S79', 'name' => 'Cedera pinggul/paha lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S80', 'name' => 'Cedera lutut/kaki superfisial', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S81', 'name' => 'Luka terbuka lutut/kaki', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S82', 'name' => 'Fraktur tungkai bawah', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S83', 'name' => 'Dislokasi lutut', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S84', 'name' => 'Cedera saraf tungkai', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S85', 'name' => 'Cedera pembuluh tungkai', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S86', 'name' => 'Cedera otot tungkai', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S87', 'name' => 'Cedera remuk tungkai', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S88', 'name' => 'Amputasi tungkai', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S89', 'name' => 'Cedera tungkai lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S90', 'name' => 'Cedera pergelangan/kaki superfisial', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S91', 'name' => 'Luka terbuka pergelangan/kaki', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S92', 'name' => 'Fraktur kaki', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S93', 'name' => 'Dislokasi pergelangan/kaki', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S94', 'name' => 'Cedera saraf kaki', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S95', 'name' => 'Cedera pembuluh kaki', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S96', 'name' => 'Cedera otot kaki', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S97', 'name' => 'Cedera remuk kaki', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S98', 'name' => 'Amputasi kaki', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'S99', 'name' => 'Cedera kaki lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T00', 'name' => 'Cedera superfisial multiple', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T01', 'name' => 'Luka terbuka multiple', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T02', 'name' => 'Fraktur multiple', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T03', 'name' => 'Dislokasi multiple', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T04', 'name' => 'Cedera remuk multiple', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T05', 'name' => 'Amputasi multiple', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T06', 'name' => 'Cedera multiple lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T07', 'name' => 'Cedera multiple tidak ditentukan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T08', 'name' => 'Fraktur tulang belakang', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T09', 'name' => 'Cedera trunkus lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T10', 'name' => 'Fraktur ekstremitas atas', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T11', 'name' => 'Cedera ekstremitas atas lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T12', 'name' => 'Fraktur ekstremitas bawah', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T13', 'name' => 'Cedera ekstremitas bawah lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T14', 'name' => 'Cedera tubuh tidak ditentukan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T15', 'name' => 'Benda asing di mata', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T16', 'name' => 'Benda asing di telinga', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T17', 'name' => 'Benda asing di saluran napas', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T18', 'name' => 'Benda asing di saluran cerna', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T19', 'name' => 'Benda asing di saluran kemih', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T20', 'name' => 'Luka bakar kepala/leher', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T21', 'name' => 'Luka bakar trunkus', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T22', 'name' => 'Luka bakar bahu/lengan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T23', 'name' => 'Luka bakar pergelangan/tangan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T24', 'name' => 'Luka bakar pinggul/tungkai', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T25', 'name' => 'Luka bakar pergelangan/kaki', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T26', 'name' => 'Luka bakar mata', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T27', 'name' => 'Luka bakar saluran napas', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T28', 'name' => 'Luka bakar organ dalam', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T29', 'name' => 'Luka bakar multiple', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T30', 'name' => 'Luka bakar tidak ditentukan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T31', 'name' => 'Luka bakar berdasarkan luas', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T32', 'name' => 'Korosi berdasarkan luas', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T33', 'name' => 'Radang dingin superfisial', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T34', 'name' => 'Radang dingin dengan nekrosis', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T35', 'name' => 'Radang dingin multiple', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T36', 'name' => 'Keracunan antibiotik', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T37', 'name' => 'Keracunan antiinfeksi', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T38', 'name' => 'Keracunan hormon', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T39', 'name' => 'Keracunan analgesik', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T40', 'name' => 'Keracunan narkotik', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T41', 'name' => 'Keracunan anestesi', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T42', 'name' => 'Keracunan antiepilepsi', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T43', 'name' => 'Keracunan psikotropik', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T44', 'name' => 'Keracunan otonomik', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T45', 'name' => 'Keracunan sistemik lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T46', 'name' => 'Keracunan kardiovaskular', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T47', 'name' => 'Keracunan pencernaan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T48', 'name' => 'Keracunan pernapasan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T49', 'name' => 'Keracunan topikal', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T50', 'name' => 'Keracunan diuretik', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T51', 'name' => 'Efek toksik alkohol', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T52', 'name' => 'Efek toksik pelarut', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T53', 'name' => 'Efek toksik halogen', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T54', 'name' => 'Efek toksik korosif', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T55', 'name' => 'Efek toksik sabun', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T56', 'name' => 'Efek toksik logam', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T57', 'name' => 'Efek toksik senyawa anorganik', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T58', 'name' => 'Efek toksik CO', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T59', 'name' => 'Efek toksik gas', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T60', 'name' => 'Efek toksik pestisida', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T61', 'name' => 'Efek toksik seafood', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T62', 'name' => 'Efek toksik makanan lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T63', 'name' => 'Efek toksik racun hewan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T64', 'name' => 'Efek toksik aflatoksin', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T65', 'name' => 'Efek toksik zat lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T66', 'name' => 'Efek radiasi', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T67', 'name' => 'Heat stroke', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T68', 'name' => 'Hipotermia', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T69', 'name' => 'Efek suhu rendah lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T70', 'name' => 'Efek tekanan udara', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T71', 'name' => 'Asfiksia', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T73', 'name' => 'Efek deprivasi lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T74', 'name' => 'Sindrom kekerasan', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T75', 'name' => 'Efek kekuatan eksternal lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T78', 'name' => 'Efek merugikan lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T79', 'name' => 'Komplikasi trauma awal', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T80', 'name' => 'Komplikasi infus', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T81', 'name' => 'Komplikasi prosedur', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T82', 'name' => 'Komplikasi alat jantung', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T83', 'name' => 'Komplikasi alat urinari', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T84', 'name' => 'Komplikasi alat ortopedi', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T85', 'name' => 'Komplikasi alat lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T86', 'name' => 'Komplikasi transplantasi', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T87', 'name' => 'Komplikasi amputasi', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T88', 'name' => 'Komplikasi lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T90', 'name' => 'Sekuela cedera kepala', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T91', 'name' => 'Sekuela cedera leher', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T92', 'name' => 'Sekuela cedera ekstremitas atas', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T93', 'name' => 'Sekuela cedera ekstremitas bawah', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T94', 'name' => 'Sekuela cedera multiple', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T95', 'name' => 'Sekuela luka bakar', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T96', 'name' => 'Sekuela keracunan obat', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T97', 'name' => 'Sekuela keracunan zat', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'T98', 'name' => 'Sekuela efek eksternal lain', 'category' => 'Cedera', 'is_active' => true],
            ['code' => 'Z00', 'name' => 'Pemeriksaan umum', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z01', 'name' => 'Pemeriksaan khusus', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z02', 'name' => 'Pemeriksaan administrasi', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z03', 'name' => 'Observasi medis', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z04', 'name' => 'Pemeriksaan tujuan lain', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z08', 'name' => 'Pemeriksaan follow-up neoplasma', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z09', 'name' => 'Pemeriksaan follow-up lain', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z10', 'name' => 'Skrining kesehatan', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z11', 'name' => 'Skrining infeksi', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z12', 'name' => 'Skrining neoplasma', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z13', 'name' => 'Skrining penyakit lain', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z20', 'name' => 'Kontak dengan infeksi', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z21', 'name' => 'HIV asimtomatik', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z22', 'name' => 'Karier infeksi', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z23', 'name' => 'Imunisasi', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z24', 'name' => 'Vaksinasi virus', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z25', 'name' => 'Vaksinasi virus lain', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z26', 'name' => 'Vaksinasi bakteri', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z27', 'name' => 'Vaksinasi kombinasi', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z28', 'name' => 'Imunisasi tidak dilakukan', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z29', 'name' => 'Imunisasi lain', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z30', 'name' => 'Kontrasepsi', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z31', 'name' => 'Kesuburan', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z32', 'name' => 'Tes kehamilan', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z33', 'name' => 'Kehamilan', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z34', 'name' => 'Perawatan kehamilan normal', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z35', 'name' => 'Perawatan kehamilan risiko', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z36', 'name' => 'Skrining antenatal', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z37', 'name' => 'Hasil persalinan', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z38', 'name' => 'Bayi lahir', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z39', 'name' => 'Perawatan nifas', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z40', 'name' => 'Prosedur profilaksis', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z41', 'name' => 'Prosedur non-terapi', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z42', 'name' => 'Perawatan rekonstruksi', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z43', 'name' => 'Perawatan stoma', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z44', 'name' => 'Pemasangan prostesis', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z45', 'name' => 'Penyesuaian alat', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z46', 'name' => 'Pemasangan alat lain', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z47', 'name' => 'Perawatan ortopedi', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z48', 'name' => 'Perawatan pasca operasi', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z49', 'name' => 'Perawatan dialisis', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z50', 'name' => 'Terapi rehabilitasi', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z51', 'name' => 'Perawatan medis lain', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z52', 'name' => 'Donor', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z53', 'name' => 'Prosedur tidak dilakukan', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z54', 'name' => 'Masa pemulihan', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z55', 'name' => 'Masalah pendidikan', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z56', 'name' => 'Masalah pekerjaan', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z57', 'name' => 'Paparan okupasi', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z58', 'name' => 'Masalah lingkungan', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z59', 'name' => 'Masalah perumahan', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z60', 'name' => 'Masalah sosial', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z61', 'name' => 'Masalah psikososial anak', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z62', 'name' => 'Masalah pengasuhan', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z63', 'name' => 'Masalah keluarga', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z64', 'name' => 'Masalah perilaku', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z65', 'name' => 'Masalah psikososial lain', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z70', 'name' => 'Konseling seksual', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z71', 'name' => 'Konseling medis', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z72', 'name' => 'Masalah gaya hidup', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z73', 'name' => 'Masalah manajemen hidup', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z74', 'name' => 'Masalah ketergantungan', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z75', 'name' => 'Masalah fasilitas', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z76', 'name' => 'Kontak dengan fasilitas', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z80', 'name' => 'Riwayat keluarga neoplasma', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z81', 'name' => 'Riwayat keluarga mental', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z82', 'name' => 'Riwayat keluarga penyakit lain', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z83', 'name' => 'Riwayat keluarga lain', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z85', 'name' => 'Riwayat neoplasma', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z86', 'name' => 'Riwayat penyakit lain', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z87', 'name' => 'Riwayat kondisi lain', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z88', 'name' => 'Riwayat alergi obat', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z89', 'name' => 'Kehilangan anggota gerak', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z90', 'name' => 'Kehilangan organ', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z91', 'name' => 'Riwayat risiko lain', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z92', 'name' => 'Riwayat pengobatan', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z93', 'name' => 'Stoma', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z94', 'name' => 'Transplantasi organ', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z95', 'name' => 'Implan kardiovaskular', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z96', 'name' => 'Implan lain', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z97', 'name' => 'Alat bantu', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z98', 'name' => 'Kondisi pasca prosedur lain', 'category' => 'Faktor Kesehatan', 'is_active' => true],
            ['code' => 'Z99', 'name' => 'Ketergantungan alat', 'category' => 'Faktor Kesehatan', 'is_active' => true],
        ];

        foreach ($diagnoses as $diagnosis) {
            DB::table('icd10_diagnoses')->insert($diagnosis);
        }
    }

    public function down(): void
    {
        DB::table('icd10_diagnoses')->truncate();
    }
};
